name: shellstone
version: 0.1.4
homepage: https://github.com/lteacher/shellstone
authors:
- Hugo Armstrong <@lteacher>
description:
  Inspired by Shelf, Redstone and js frameworks like Sails, Shellstone is a server
  side framework to provide a form of ORM, routing and other various features

environment:
    sdk: ">=1.8.0 <2.0.0"

dependencies:
  collection: '>=1.5.1 <2.0.0'
  sqljocky: '>=0.14.1 <0.15.0'
  quiver: '>=0.22.0 <0.23.0'
  postgresql:
    git:
      url: https://github.com/lteacher/dart_postgresql.git
      ref: feature/#75-multi
dev_dependencies:
  test: '^0.12.0'
  matcher: '0.12.0+2'
