name: shellstone
version: 0.1.0
homepage: https://github.com/lessonteacher/shellstone
authors:
- Hugo Armstrong <@lessonteacher>
description:
  An attempt at producing a Redstone / Shelf based package to also do some ORM
  functionality

dependencies:
  redstone: '0.6.5'
  collection: '^1.5.1'
  sqljocky: '0.14.1'
  quiver: '>=0.22.0 <0.23.0'
dev_dependencies:
  test: '^0.12.0'
  matcher: '0.12.0+2'
  grinder: "^0.8.0+2"
